# Docker produccion o stage
FROM python:3.8.3-buster

ENV RABBIT_URL host.docker.internal
ENV MONGO_URL host.docker.internal
ENV AUTH_SERVICE_URL host.docker.internal
ENV AUTH_SERVICE_PORT 3000

WORKDIR /app
RUN curl -L https://github.com/nmarsollier/ecommerce_catalog_python/tarball/master | tar xz --strip=1
RUN pip install -U -r requirements.txt

# Puerto de Auth Service
EXPOSE 3002

CMD python run.py
